### ISSUE TITLE
'module' object has no attribute 'register_namespace'

### ISSUE THREAD

**Issue by fhanif-dincloud** [vcatalano/py-authorize#23]
As per my understanding, this issue is only on CentOS machines and having python 2.6.6.
What is the best way to come out from this. Further more, here is the exception location.

/usr/lib/python2.6/site-packages/Py_Authorize-1.2.2.0-py2.6.egg/authorize/apis/authorize_api.py in <module>, line 20

Please respond this with some best possible solutions. I am restricted to use CentOS.

**Comment by shallot** [comment]
JFTR one can get a newer ElementTree that supports `register_namespace()` on CentOS 6 by doing `sudo pip install --upgrade lxml` (with a few prerequisites satisfied), but you also have to make sure the `import` logic tries the one in `lxml` in addition to the one from `xml.etree`.
