### ISSUE TITLE
Cannot submit masked card numbers on update

### ISSUE THREAD

**Issue by clintecker** [vcatalano/py-authorize#30]
When submitting a `updateCustomerPaymentProfileRequest`, in `authorize.CreditCard.update` the CIM developer guide states the following for the format of the `cardNumber`:

----
**Value:** The customer’s credit card number
**Format:** 13 to 16 digits

Number can also be masked, for example, XXXX1111

**Notes:** If the value is masked, the last four digits must match the original value in the profile. 

If a masked value is submitted, the original value will not be updated

----

However the CreditCardSchema enforces that the value of the `card_number` should validate against `colander.luhnok` and rejects these.  It also rejects the request if I omit the `card_number` completely.

Any suggestions on how to proceed here?

**Comment by vcatalano** [comment]
I've updated how masking is now handled for updating an existing credit card. Developers can provide either the last 4 digits or the masked card number e.g. XXXX1234.
