### ISSUE TITLE
Add duplicate_window parameter

### ISSUE THREAD

**Issue by filipeximenes** [vcatalano/py-authorize#42]
Hi, I'm trying to add this duplicate_window parameter to the lib but i'm having a hard time.
You can see my last commits here: https://github.com/Axilent/py-authorize

This is the documentation: https://support.authorize.net/authkb/index?page=content&id=A425

But I'm getting this in response:
```
{
  "messages": [
    {
      "message": {
        "text": "The element 'transactionRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'duplicateWindow' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'currencyCode, payment, profile, solution, callId, authCode, refTransId, splitTenderId, order, lineItems, tax, duty, shipping, taxExempt, poNumber, customer, billTo, shipTo, customerIP, cardholderAuthentication, retail, employeeId, transactionSettings, userFields' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.", 
        "code": "E00003"
      }, 
      "result_code": "Error"
    }
  ]
}
```
I've never done RPC, could you give me some help?

**Comment by vcatalano** [comment]
The structure for adding the duplicateWindow field to an transaction can be found in the AIM XML documentation: http://www.authorize.net/support/AIM_guide_XML.pdf. The field is part of the `transactionSettings` section of the `createTransactionRequest` request. I would recommend implementing this within the `transaction_api.py`. I'm not sure why this field is only used for AIM and not CIM transactions, but if this implement this, we may need to note in the documentation that this only applies to AIM transactions.

**Comment by vcatalano** [comment]
I've merged your branch in to master so I'm closing out this issue.
