### ISSUE TITLE
AttributeError: type object 'Configuration' has no attribute 'api'

### ISSUE THREAD

**Issue by shaunc869** [vcatalano/py-authorize#49]
Hi!

When I am trying to do a:

result = authorize.Transaction.sale({
            'amount': amount,
            'customer_id': cust_id
            'payment_id': pay_id
        })

Any ideas? Thank you!

**Comment by vcatalano** [comment]
Before running any commands you must first run the `configure` function:

```
authorize.Configuration.configure(
    authorize.Environment.TEST,
    'api_login_id',
    'api_transaction_key',
)
```

**Comment by shaunc869** [comment]
Yup, totally being dumb, sorry about that and thanks for the help!
