### ISSUE TITLE
Thread safety concerns

### ISSUE THREAD

**Issue by MRSalomao** [vcatalano/py-authorize#54]
Hi, can this library be used in a thread safe way?

Specifically, I'm concerned that the configuration.py file won't allow for different API_LOGIN_ID / TRANSACTION_KEY pairs active at the same time, in different threads:

class Configuration(object):

    @staticmethod
    def configure(environment, login_id, transaction_key):
        Configuration.environment = environment
        Configuration.login_id = login_id
        Configuration.transaction_key = transaction_key
        Configuration.api = AuthorizeAPI(Configuration.instantiate())

    @staticmethod
    def instantiate():
        return Configuration(
            Configuration.environment,
            Configuration.login_id,
            Configuration.transaction_key,
        )

    def __init__(self, environment, login_id, transaction_key):
        self.environment = environment
        self.login_id = login_id
        self.transaction_key = transaction_key

**Comment by vcatalano** [comment]
If you find yourself needing to integrate with multiple Authorize.net accounts (API_LOGIN_ID / TRANSACTION_KEY pairs), you can use the [Advanced Configuration](http://vcatalano.github.io/py-authorize/advanced.html) primarily the [Mutliple Gateway Configuration](http://vcatalano.github.io/py-authorize/advanced.html#multiple-gateway-configurations).

Using this approach, you would create new `Configuration` instances with your login and transaction keys and then make your call on that config's API:

```python
config = authorize.Configuration(
    Environment.PRODUCTION,
    'api_login_id',
    'api_transaction_key',
)

config.api.transaction.sale({
    'amount': 40.00,
    'credit_card': {
        'card_number': '4111111111111111',
        'expiration_date': '04/2014',
    }
})
```

**Comment by MRSalomao** [comment]
Perfect! Thank you.
